### ISSUE TITLE
Clone openshift-ansible style guide and apply it here

### ISSUE THREAD

**Issue by jscar-hawk** [redhat-cop/automation-good-practices#12]
Upon looking for input from other Red Hatters on ansible playbook Style Guides,
It was suggested that we use "openshift-ansible Style Guide"
https://github.com/openshift/openshift-ansible/blob/master/docs/style_guide.adoc

**Comment by ericzolf** [comment]
It's a duplicate of #2 isn't it?

**Comment by jscar-hawk** [comment]
Yes you are correct. I'll close out this issue and start working on #2
