### ISSUE TITLE
reuse stuff from the OpenShift Ansible guideline

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automation-good-practices#2]
https://github.com/openshift/openshift-ansible/blob/master/docs/style_guide.adoc and/or https://github.com/openshift/openshift-ansible/blob/master/docs/best_practices_guide.adoc

**Comment by jscar-hawk** [comment]
Yes, you are right. I'll start working on it and close this issue.

**Comment by ericzolf** [comment]
I went through the style guide and analyzed it:

* line length _should_ be shorter than 80 chars and _must_ be shorter than 120 chars -> we don't have such a rule, do we care (AgnosticD calls for 150 characters and I've already hit it)
* use .yml not .yaml -> we already have it
* cli cli_ and global g_ variables -> very specific and somewhat contradictory to having the `__` prefix for private variables
* role variable prefix -> same idea but contradictory to our approach with the full role name (though I also tend to shorten the role name if too long), and I don't like the statement that name conflict isn't a big issue (it ignores the usage of inventories). I would leave as is, we could just state that a shorter name is fine.

**Comment by ericzolf** [comment]
Then I analyzed the best practice guide:

1. When adding a new parameter to an existing method, a default value SHOULD be used -> good to take IMHO
2. Pylint rules -> it's a specific tool, we could add it as an example to our (one!) Python recommendation about style, but not more
3. Ansible files SHOULD NOT use JSON (use pure YAML instead) -> sounds obvious but we can add it
4. Custom Ansible modules SHOULD be embedded in a role -> outdated, we prefer collections...
5. Parameters to Ansible modules SHOULD use the Yaml dictionary -> must use it (we already have the rule to _not_ use the old `key=value` style)
6. The Ansible command module SHOULD be used instead of the Ansible shell module -> we have it already
7. The Ansible quote filter MUST be used with any variable passed into the shell module. -> that's a good one, we should add it
8. defensive programming / begin with checks for any variables that they require -> IMHO it's only useless code that needs to be maintained, better is to make sure that the code fails cleanly if the variable isn't declared and can be properly restarted (idempotent). If you want to be sure it looks fine, use the `--check` mode.
9. Ansible tasks SHOULD NOT be used in Ansible playbooks. Instead, use pre_tasks and post_tasks. -> it's worth discussing, but probably a bit oudated with include/import_roles. IMHO it should be written: use either roles _or_ tasks, not both.
10. All tasks in a role SHOULD be tagged with the role name -> conflicts with our recommendation to _not_ use tags in roles.
11. The Ansible roles directory MUST maintain a flat structure -> obvious but we can add the rule
12. Ansible Roles SHOULD be named like technology_component[_subcomponent]. -> I don't fully agree, it's generally something like component_action, but we should discuss it.
13. The default filter SHOULD replace empty strings, lists, etc. -> it might be better to let the code fail if the variable isn't defined and it's generally not true for variables in roles (defaults are to be documented in `defaults/main.yml`)
14. Package installation MUST use Ansible package module to abstract away dnf/yum -> outdated, dnf and yum are more less equivalent now, and more powerful

**Comment by ericzolf** [comment]
Discussion 2021-11-17 CoP:
1. only recommendation to limit line size + examples to do it
2. JSON vs. YAML -> whatever is more readable
3. regarding defensive programming, we are _against_ it, and we should also add a rule that it's better to fail than do the wrong (no sound default present).
4. use either roles or tasks, not both; 
5. avoid numbering of tasks, roles and playbooks
6. role naming object_action for better sorting
7. unless you need the abstraction of package, stick with the native yum/dnf package, it has more options and the package names are generally anyway different.
