### ISSUE TITLE
RFE: please add instructions or Makefile to build PDF

### ISSUE THREAD

**Issue by pcfe** [redhat-cop/automation-good-practices#21]
in db2883884c26f53d20bcc6f4d1149b236735fc00 asciidoctor-pdf is mentioned.
It would be nice if the docs also showed users and/or potential contributors the command to use, just like they show how to generate HTML, or if a `Makefile` was added.

MR coming in a moment.

pcfe

**Comment by ericzolf** [comment]
Not sure why this didn't happen automatically, but closed with #22
