### ISSUE TITLE
GH pages lack images

### ISSUE THREAD

**Issue by pcfe** [redhat-cop/automation-good-practices#25]
there's no _Figure 1._ at https://redhat-cop.github.io/automation-good-practices/#_define_which_structure_to_use_for_which_purpose

pretty sure I saw the image rendered there before, but I might mis-remember as I also read the AGP in PDF format.

Since a pic says more than a thousand words;
![Screenshot_20210725_131925](https://user-images.githubusercontent.com/3717066/126897295-c50152a4-ae8a-4c66-9a69-fe2ff9c97694.png)

**Comment by ericzolf** [comment]
I was convinced that I had fixed the issue but it seems that the picture isn't copied over... Not sure why not. I'll have a look.
