### ISSUE TITLE
Updating all packages guidance

### ISSUE THREAD

**Issue by bontreger** [redhat-cop/automation-good-practices#59]
Include some guidance around updating all packages

example:

yum:
  state: latest
  name: "*"
  update_only: yes

**Comment by bontreger** [comment]
Client issue seen in the field, making an issue so I can remember and go back when I have the cycle to do so

**Comment by ericzolf** [comment]
We should probably be wary of expressing recommendations for specific modules, it could go through the roof, but I'm happy to have the discussion.

**Comment by bontreger** [comment]
Yeah, the more I talk with others about this particular issue, it's better suited being brought into the official docs

Short of it, this playbook does what you'd expect
- name: install every package available
  yum:
    state: present
    name: "*"
    
    
and this isn't documented behavior
