### ISSUE TITLE
publish docs automatically

### ISSUE THREAD

**Issue by jeichler** [redhat-cop/automation-good-practices#81]
currently the docs are fairly behind the current main branch.
Ideally docs are published after a merge into the main branch (kinda like version "latest").

thoughts?

**Comment by djdanielsson** [comment]
I agree, it should be on commit it re-publishes them

**Comment by ericzolf** [comment]
My initial idea was to push regularly versions, which would trigger the build, but I agree that it doesn't really work well and was probably over-engineered.

**Comment by ericzolf** [comment]
I just pushed v2022-12-15-12 so we're up-to-date again, but still agreed that we don't need the overhead.

**Comment by ericzolf** [comment]
IMHO, what needs to be done:

- [ ] update the pipeline to re-create the website on merged PRs resp. modified main branch
- [ ] add a variable/placeholder in the documentation and some code to automatically do versioning based on Git commit date (like CER does)

**Comment by Fale** [comment]
@ericzolf what do you mean by "CER" in this context?
