### ISSUE TITLE
Image variable_precedences.png is not published

### ISSUE THREAD

**Issue by CarstenGrohmann** [redhat-cop/automation-good-practices#82]
Hi,

in the [documenation](https://redhat-cop.github.io/automation-good-practices/) the image "Figure 2. Flow of variable precedences" is not shown. It looks like the file `variable_precedences.png` is not published, but the first image `ansible_structures.svg` (Figure 1. Structure of Automation) has been published.

Please publish `variable_precedences.png`.

Thank you,
Carsten

**Comment by CarstenGrohmann** [comment]
@mophahr Thank you for fixing this issue. Unfortunately, the pipeline did not run completely, so the new version has not been built and released yet. Please restart the build pipeline.

**Comment by mophahr** [comment]
@CarstenGrohmann seem like this was fixed by a recent PR by @Fale
