### ISSUE TITLE
Broken link to docs.adfinis-sygroup.ch

### ISSUE THREAD

**Issue by CarstenGrohmann** [redhat-cop/automation-good-practices#89]
The document at https://docs.adfinis-sygroup.ch/public/ansible-guide/overview.html no longer exists, and the entire domain is also no longer registered in the DNS.

https://github.com/redhat-cop/automation-good-practices/blob/886a5fabbd4c2776c60b60e322ed99f9d27ba4cb/roles/README.adoc?plain=1#L473

**Comment by jeichler** [comment]
I dont know what the original content looked like but could be the content from here: https://adfinis.github.io/ansible-guide/ (respectively the github repo as a source: https://github.com/adfinis/ansible-guide) ?
